# Generated by Django 5.1.6 on 2025-05-01 14:50

import api.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(default=django.utils.timezone.now, validators=[api.validators.validate_min_data])),
            ],
        ),
    ]
